Class {
	#name : #PEPluggableTextMorphPlus,
	#superclass : #PluggableTextMorphPlus,
	#category : #PixelEditor
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LW 6/10/2024 18:47'
}
PEPluggableTextMorphPlus >> vScrollBarPolicy [

	^ #never
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LW 6/10/2024 19:34'
}
PEPluggableTextMorphPlus >> wantsFrameAdornments [

	^ false
]
